### ISSUE TITLE
loadRequest() doesn't support headers / body / post / update / delete

### ISSUE THREAD

**Issue by AmirHosseinAsa** [jakky1/webview_win_floating#11]
I need to change the method and add a body of  loadRequest.
How can I do this?

**Comment by jakky1** [comment]
This package doesn't support these.
I have no plan to support.

**Comment by jakky1** [comment]
Since there are  some news about [web phishing by webview2 cookies](https://www.ghacks.net/2022/06/27/new-windows-phishing-method-gives-attackers-access-to-cookies-and-more/),
so I try not to provide some functions if I think they can be used in some illegal purpose,
even though I know the webview_flutter provide them.

Hmm... so far I only see news about the cookies can be used to phishing,
however I think (guess) there may have the same issue with headers / httpMethod related functions?
That's why I said I have no plan to implement them.

Of course maybe there are some legal usage but I just don't know it.
Currently I think most of the cases can be done without these functions.

If anyone can tell me why these functions are so important and for which use cases,
then maybe I can consider to implement them (if possible).

**Comment by husnain067** [comment]
I think headers are a common thing many of the sites are not publicly accessed in our case web-view URL is only accessed by people login the app using the token
