### ISSUE TITLE
Not working if installing into "C:/Program Files (x86)" system dir

### ISSUE THREAD

**Issue by mohgit97** [jakky1/webview_win_floating#19]
when i build the app and build exe installer the webview doesnt show

**Comment by jakky1** [comment]
I try to build debug & release and it works for me, with latest version  `2.2.4`

Please give me a sample code ( < 200 lines ) that can duplicate this issue.

**Comment by mohgit97** [comment]
the problem occurswhen create setup file with inno setup

**Comment by jakky1** [comment]
Referring to the [link](https://medium.com/@fluttergems/packaging-and-distributing-flutter-desktop-apps-the-missing-guide-part-2-windows-0b468d5e9e70)

I try to create an iss setup file,
and launch it, 
select "install for all users",
select default installation path "C:\Program Files\My Program", 
then install it, and run it,
the webview not shown

BUT... BUT...
if you select installation path as "C:\My Program",
or you select "install for me only" at the beginning,
the webview shown and works well ~~~~~~~~~~~~~

So I think there maybe something we need to do more config
to make it works when installing in "C:\Program Files\" system dir.

Since it works if you install to "C:\My Program",
I think this issue is not related to `webview_win_floating`.
Maybe you should do more survey on InnoSetup.

If no any further question, I will close this issue.

**Comment by jakky1** [comment]
In this [link](https://github.com/MicrosoftEdge/WebView2Feedback/issues/297),
webview cannot create cache dir if exe file is in "C:/Program Files (x86)",
so webview create won't work.

In this case,
please specify the data folder for the webview with the following code:
```
  final controller = WebViewController.fromPlatformCreationParams(
    const WindowsPlatformWebViewControllerCreationParams(
      userDataFolder: "c:\\cache_webview"));
```

If you are using `WinWebViewController`, use the following code instead:
```
  final controller = WinWebViewController(userDataFolder: "c:\\cache_webview");
```

**Comment by mohgit97** [comment]
thanks for your help i figure it out .thanke you so much

**Comment by mohgit97** [comment]
When i try to embed youtube video it showing the video frame like having marging to the left

**Comment by jakky1** [comment]
@mohgit97 
For youtube related issue,
Please open a new issue
And give me more detail and screenshot.
