### ISSUE TITLE
Cookies and session not available for flutter dekstop windows 

### ISSUE THREAD

**Issue by herve2000** [jakky1/webview_win_floating#8]
Je n'arrive pas à faire préciser les cookies et session dans la webview

**Comment by jakky1** [comment]
About session,
the official package ``webview_flutter`` also not provide session-related methods, 
and I will follow this API and wont provide session-related functions.

About cookie, 
since there are some news about [web phishing by webview2 cookies](https://www.ghacks.net/2022/06/27/new-windows-phishing-method-gives-attackers-access-to-cookies-and-more/),
of course I think most of us won't do that (phishing),
however I won't provide any cooke get / set methods in this package.

So this issue won't fix
